/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ObjectArrayTest */
#include <stdio.h>
#include "ObjectArrayTest.h"

JNIEXPORT jobjectArray JNICALL Java_ObjectArrayTest_initInt2DArray
(JNIEnv *env, jclass cls, int size){
	jobjectArray result;
	int i ;
	jclass intArrCls = env->FindClass("[I");
	if (NULL == intArrCls){
		return NULL;
	}

	result = env->NewObjectArray(size,intArrCls,NULL);
	if (NULL == result){
		return NULL;
	}
	for (i = 0 ; i < size ; i ++){
		jint tmp[256];
		int j ;
		jintArray iarr = env->NewIntArray(size);
		if (NULL == iarr){
			return NULL;
		}
		for (j = 0 ; j < size ; j ++){
			tmp[j] = j  + i;
		}
		env->SetIntArrayRegion(iarr,0,size,tmp);
		env->SetObjectArrayElement(result,i,iarr);
		env->DeleteLocalRef(iarr);
	}
	return result;
}
